---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ambassador-certs
  namespace: default
spec:
  secretName: ambassador-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mercury.*.net
  dnsNames:
  - mercury.*.net
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - mercury.*.net
