---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ambassador-certs
  namespace: default
spec:
  secretName: ambassador-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mercury.*.net
  dnsNames:
  - mercury.*.net
  - "*.mercury.*.net"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
