---
alertmanager:
  persistentVolume:
    enabled: true
    storageClassName: rook-ceph-block
    size: 1Gi
server:
  persistentVolume:
    enabled: true
    storageClassName: rook-ceph-block
    retention: "3d"
    size: 3Gi
