apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  extraArgs:
    kubelet-preferred-address-types: "InternalIP,ExternalIP,Hostname"
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    provider-id: "digitalocean://$DROPLET_ID"
